[package]
name = "apter"
version = "0.1.0"
edition = "2021"
description = "Apter Trees in Rust"
license = "GPL-3.0-or-later"
documentation = "https://docs.rs/apter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
